export default function(){
  var africa = {
    name: 'Africa',
    subRegions: [
    { name: 'Eastern Africa',
      countries: [
        { name: 'Burundi', flag: 'burundi-flag.svg', emblem: 'burundi-emblem.svg', orthographic: 'burundi-orthographic.svg'},
        { name: 'Comoros', flag: 'comoros-flag.svg', emblem: 'comoros-emblem.svg', orthographic: 'comoros-orthographic.svg'},
        { name: 'Djibouti', flag: 'djibouti-flag.svg', emblem: 'djibouti-emblem.svg', orthographic: 'djibouti-orthographic.svg'},
        { name: 'Eritrea', flag: 'eritrea-flag.svg', emblem: 'eritrea-emblem.svg', orthographic: 'eritrea-orthographic.svg'},
        { name: 'Ethiopia', flag: 'ethiopia-flag.svg', emblem: 'ethiopia-emblem.svg', orthographic: 'eritrea-orthographic.svg'},
        { name: 'Kenya', flag: 'kenya-flag.svg', emblem: 'kenya-emblem.svg', orthographic: 'kenya-orthographic.svg'},
        { name: 'Madagascar', flag: 'madagascar-flag.svg', emblem: 'madagascar-emblem.svg', orthographic: 'madagascar-orthographic.svg'},
        { name: 'Malawi', flag: 'malawi-flag.svg', emblem: 'malawi-emblem.svg', orthographic: 'malawi-orthographic.svg'},
        { name: 'Mauritius', flag: 'mauritius-flag.svg', emblem: 'mauritius-emblem.svg', orthographic: 'mauritius-orthographic.svg'},
        { name: 'Mayotte', flag: 'mayotte-flag.svg', emblem: 'mayotte-emblem.svg', orthographic: 'mayotte-orthographic.svg'},
        { name: 'Mozambique', flag: 'mozambique-flag.svg', emblem: 'mozambique-emblem.svg', orthographic: 'mozambique-orthographic.svg'},
        { name: 'Reunion', flag: 'reunion-flag.svg', emblem: 'reunion-emblem.svg', orthographic: 'reunion-orthographic.svg'},
        { name: 'Rwanda', flag: 'rwanda-flag.svg', emblem: 'rwanda-emblem.svg', orthographic: 'rwanda-orthographic.svg'},
        { name: 'Seychelles', flag: 'seychelles-flag.svg', emblem: 'seychelles-emblem.svg', orthographic: 'seychelles-orthographic.svg'},
        { name: 'Somalia', flag: 'somalia-flag.svg', emblem: 'somalia-emblem.svg', orthographic: 'somalia-orthographic.svg'},
        { name: 'South Sudan', flag: 'south-sudan-flag.svg', emblem: 'south-sudan-emblem.svg', orthographic: 'south-sudan-orthographic.svg'},
        { name: 'Tanzania', flag: 'tanzania-flag.svg', emblem: 'tanzania-emblem.svg', orthographic: 'tanzania-orthographic.svg'},
        { name: 'Uganda', flag: 'uganda-flag.svg', emblem: 'uganda-emblem.svg', orthographic: 'uganda-orthographic.svg'},
        { name: 'Zambia', flag: 'zambia-flag.svg', emblem: 'zambia-emblem.svg', orthographic: 'zambia-orthographic.svg'},
        { name: 'Zimbabwe', flag: 'zimbabwe-flag.svg', emblem: 'zimbabwe-emblem.svg', orthographic: 'zimbabwe-orthographic.svg'},
    ]},
    {
      name: 'Middle Africa',
      countries: [
        { name: 'Angola', flag: 'angola-flag.svg', emblem: 'angola-emblem.svg', orthographic: 'angola-orthographic.svg'},
        { name: 'Cameroon', flag: 'cameroon-flag.svg', emblem: 'cameroon-emblem.svg', orthographic: 'cameroon-orthographic.svg'},
        { name: 'Central African Republic', flag: 'central-african-republic-flag.svg', emblem: 'central-african-republic-emblem.svg', orthographic: 'central-african-republic-orthographic.svg'},
        { name: 'Chad', flag: 'chad-flag.svg', emblem: 'chad-emblem.svg', orthographic: 'chad-orthographic.svg'},
        { name: 'the Democratic Republic of the Congo', flag: 'democratic-republic-of-the-congo-flag.svg', emblem: 'democratic-republic-of-the-congo-emblem.svg', orthographic: 'democratic-republic-of-the-congo-orthographic.svg'},
        { name: 'Equatorial Guinea', flag: 'equatorial-guinea-flag.svg', emblem: 'equatorial-guinea-emblem.svg', orthographic: 'equatorial-guinea-orthographic.svg'},
        { name: 'Gabon', flag: 'gabon-flag.svg', emblem: 'gabon-emblem.svg', orthographic: 'gabon-orthographic.svg'},
        { name: 'the Republic of the Congo', flag: 'republic-of-the-congo-flag.svg', emblem: 'republic-of-the-congo-emblem.svg', orthographic: 'republic-of-the-congo-orthographic.svg'},
        { name: 'Sao Tome and Principe', flag: 'sao-tome-and-principe-flag.svg', emblem: 'sao-tome-and-principe-emblem.svg', orthographic: 'sao-tome-and-principe-orthographic.svg'},
    ]},
    {
      name: 'Northern Africa',
      countries: [
        { name: 'Algeria', flag: 'algeria-flag.svg', emblem: 'algeria-emblem.svg', orthographic: 'algeria-orthographic.svg'},
        { name: 'Egypt', flag: 'egypt-flag.svg', emblem: 'egypt-emblem.svg', orthographic: 'egypt-orthographic.svg'},
        { name: 'Libya', flag: 'libya-flag.svg', emblem: 'libya-emblem.svg', orthographic: 'libya-orthographic.svg'},
        { name: 'Morocco', flag: 'morocco-flag.svg', emblem: 'morocco-emblem.svg', orthographic: 'morocco-orthographic.svg'},
        { name: 'Sudan', flag: 'sudan-flag.svg', emblem: 'sudan-emblem.svg', orthographic: 'sudan-orthographic.png'},
        { name: 'Tunisia', flag: 'tunisia-flag.svg', emblem: 'tunisia-emblem.svg', orthographic: 'tunisia-orthographic.svg'},
        //{ name: 'Western Sahara', flag: '-flag.svg', emblem: '-emblem.svg', orthographic: '-orthographic.svg'},
    ]},
    {
      name: 'Southern Africa',
      countries: [
        { name: 'Botswana', flag: 'botswana-flag.svg', emblem: 'botswana-emblem.svg', orthographic: 'botswana-orthographic.svg'},
        { name: 'Lesotho', flag: 'lesotho-flag.svg', emblem: 'lesotho-emblem.svg', orthographic: 'lesotho-orthographic.svg'},
        { name: 'Namibia', flag: 'namibia-flag.svg', emblem: 'namibia-emblem.svg', orthographic: 'namibia-orthographic.svg'},
        { name: 'South Africa', flag: 'south-africa-flag.svg', emblem: 'south-africa-emblem.jpg', orthographic: 'south-africa-orthographic.svg'},
        { name: 'Swaziland', flag: 'swaziland-flag.svg', emblem: 'swaziland-emblem.svg', orthographic: 'swaziland-orthographic.svg'},
    ]},
    {
      name: 'Western Africa',
      countries: [
        { name: 'Benin', flag: 'benin-flag.svg', emblem: 'benin-emblem.svg', orthographic: 'benin-orthographic.svg'},
        { name: 'Burkina Faso', flag: 'burkina-faso-flag.svg', emblem: 'burkina-faso-emblem.svg', orthographic: 'burkina-faso-orthographic.svg'},
        { name: 'Cabo Verde', flag: 'cabo-verde-flag.svg', emblem: 'cabo-verde-emblem.svg', orthographic: 'cabo-verde-orthographic.svg'},
        { name: 'Cote d\'Ivoire', flag: 'cote-divoire-flag.svg', emblem: 'cote-divoire-emblem.svg', orthographic: 'cote-divoire-orthographic.svg'},
        { name: 'the Gambia', flag: 'the-gambia-flag.svg', emblem: 'the-gambia-emblem.svg', orthographic: 'the-gambia-orthographic.svg'},
        { name: 'Ghana', flag: 'ghana-flag.svg', emblem: 'ghana-emblem.svg', orthographic: 'ghana-orthographic.svg'},
        { name: 'Guinea', flag: 'guinea-flag.svg', emblem: 'guinea-emblem.svg', orthographic: 'guinea-orthographic.svg'},
        { name: 'Guinea-Bissau', flag: 'guinea-bissau-flag.svg', emblem: 'guinea-bissau-emblem.svg', orthographic: 'guinea-bissau-orthographic.svg'},
        { name: 'Liberia', flag: 'liberia-flag.svg', emblem: 'liberia-emblem.svg', orthographic: 'liberia-orthographic.svg'},
        { name: 'Mali', flag: 'mali-flag.svg', emblem: 'mali-emblem.svg', orthographic: 'mali-orthographic.svg'},
        { name: 'Mauritania', flag: 'mauritania-flag.svg', emblem: 'mauritania-emblem.svg', orthographic: 'mauritania-orthographic.svg'},
        { name: 'Niger', flag: 'niger-flag.svg', emblem: 'niger-emblem.svg', orthographic: 'niger-orthographic.svg'},
        { name: 'Nigeria', flag: 'nigeria-flag.svg', emblem: 'nigeria-emblem.svg', orthographic: 'nigeria-orthographic.svg'},
        { name: 'Saint Helena, Ascension and Tristan da Cunha', flag: 'saint-helena-ascension-and-tristan-da-cunha-flag.svg', emblem: null, orthographic: 'saint-helena-ascension-and-tristan-da-cunha-orthographic.svg'},
        { name: 'Senegal', flag: 'senegal-flag.svg', emblem: 'senegal-emblem.svg', orthographic: 'senegal-orthographic.svg'},
        { name: 'Sierra Leone', flag: 'sierra-leone-flag.svg', emblem: 'sierra-leone-emblem.svg', orthographic: 'sierra-leone-orthographic.svg'},
        { name: 'Togo', flag: 'togo-flag.svg', emblem: 'togo-emblem.svg', orthographic: 'togo-orthographic.svg'},
    ]}
  ]};

  var americas = {
    name: 'Americas',
    subRegions: [
    {
      name: 'Caribbean',
      countries: [
      { name: 'Anguilla',
        flag: 'anguilla-flag.svg',
        emblem: 'anguilla-emblem.svg',
        orthographic: 'anguilla-orthographic.svg' },
      { name: 'Antigua and Barbuda',
        flag: 'antigua-and-barbuda-flag.svg',
        emblem: 'antigua-and-barbuda-emblem.svg',
        orthographic: 'antigua-and-barbuda-orthographic.svg' },
      { name: 'Aruba',
        flag: 'aruba-flag.svg',
        emblem: 'aruba-emblem.svg',
        orthographic: 'aruba-orthographic.svg' },
      { name: 'the Bahamas',
        flag: 'bahamas-flag.svg',
        emblem: 'bahamas-emblem.svg',
        orthographic: 'bahamas-orthographic.svg' },
      { name: 'Barbados',
        flag: 'barbados-flag.svg',
        emblem: 'barbados-emblem.svg',
        orthographic: 'barbados-orthographic.svg' },
      { name: 'Bonaire, Sint Eustatius and Saba (Caribbean Netherlands)',
        flag: 'caribbean-netherlands-flag.svg',
        emblem: 'caribbean-netherlands-emblem.svg',
        orthographic: 'caribbean-netherlands-orthographic.svg' },
      { name: 'the British Virgin Islands',
        flag: 'british-virgin-islands-flag.svg',
        emblem: 'british-virgin-islands-emblem.svg',
        orthographic: 'british-virgin-islands-orthographic.svg' },
      { name: 'the Cayman Islands',
        flag: 'cayman-islands-flag.svg',
        emblem: 'cayman-islands-emblem.svg',
        orthographic: 'cayman-islands-orthographic.svg' },
      { name: 'Cuba',
        flag: 'cuba-flag.svg',
        emblem: 'cuba-emblem.svg',
        orthographic: 'cuba-orthographic.svg' },
      { name: 'Curacao',
        flag: 'curacao-flag.svg',
        emblem: 'curacao-emblem.svg',
        orthographic: 'curacao-orthographic.svg' },
      { name: 'Dominica',
        flag: 'dominica-flag.svg',
        emblem: 'dominica-emblem.svg',
        orthographic: 'dominica-orthographic.svg' },
      { name: 'the Dominican Republic',
        flag: 'dominican-republic-flag.svg',
        emblem: 'dominican-republic-emblem.svg',
        orthographic: 'dominican-republic-orthographic.svg' },
      { name: 'Grenada',
        flag: 'grenada-flag.svg',
        emblem: 'grenada-emblem.svg',
        orthographic: 'grenada-orthographic.svg' },
      { name: 'Guadeloupe',
        flag: 'guadeloupe-flag.svg',
        emblem: null,
        orthographic: 'guadeloupe-orthographic.svg' },
      { name: 'Haiti',
        flag: 'haiti-flag.svg',
        emblem: 'haiti-emblem.svg',
        orthographic: 'haiti-orthographic.svg' },
      { name: 'Jamaica',
        flag: 'jamaica-flag.svg',
        emblem: 'jamaica-emblem.svg',
        orthographic: 'jamaica-orthographic.svg' },
      { name: 'Martinique',
        flag: 'martinique-flag.svg',
        emblem: 'martinique-emblem.svg',
        orthographic: 'martinique-orthographic.svg' },
      { name: 'Montserrat',
        flag: 'montserrat-flag.svg',
        emblem: 'montserrat-emblem.svg',
        orthographic: 'montserrat-orthographic.svg' },
      { name: 'Puerto Rico',
        flag: 'puerto-rico-flag.svg',
        emblem: 'puerto-rico-emblem.svg',
        orthographic: 'puerto-rico-orthographic.svg' },
      { name: 'Saint Kitts and Nevis',
        flag: 'saint-kitts-and-nevis-flag.svg',
        emblem: 'saint-kitts-and-nevis-emblem.svg',
        orthographic: 'saint-kitts-and-nevis-orthographic.svg' },
      { name: 'Saint Lucia',
        flag: 'saint-lucia-flag.svg',
        emblem: 'saint-lucia-emblem.svg',
        orthographic: 'saint-lucia-orthographic.svg' },
      { name: 'Saint Vincent and the Grenadines',
        flag: 'saint-vincent-and-the-grenadines-flag.svg',
        emblem: 'saint-vincent-and-the-grenadines-emblem.svg',
        orthographic: 'saint-vincent-and-the-grenadines-orthographic.svg' },
      { name: 'Sint Maarten (Dutch part)',
        flag: 'sint-maarten-flag.svg',
        emblem: 'sint-maarten-emblem.svg',
        orthographic: 'sint-maarten-orthographic.svg' },
      { name: 'Trinidad and Tobago',
        flag: 'trinidad-and-tobago-flag.svg',
        emblem: 'trinidad-and-tobago-emblem.svg',
        orthographic: 'trinidad-and-tobago-orthographic.svg' },
      { name: 'the Turks and Caicos Islands',
        flag: 'turks-and-caicos-islands-flag.svg',
        emblem: 'turks-and-caicos-islands-emblem.svg',
        orthographic: 'turks-and-caicos-islands-orthographic.svg' },
      { name: 'the United States Virgin Islands',
        flag: 'united-states-virgin-islands-flag.svg',
        emblem: 'united-states-virgin-islands-emblem.svg',
        orthographic: 'united-states-virgin-islands-orthographic.svg' } ]
  },
    {
      name: 'Central America',
      countries: [
        { name: 'Belize',
          flag: 'belize-flag.svg',
          emblem: 'belize-emblem.svg',
          orthographic: 'belize-orthographic.svg' },
        { name: 'Costa Rica',
          flag: 'costa-rica-flag.svg',
          emblem: 'costa-rica-emblem.svg',
          orthographic: 'costa-rica-orthographic.svg' },
        { name: 'El Salvador',
          flag: 'el-salvador-flag.svg',
          emblem: 'el-salvador-emblem.svg',
          orthographic: 'el-salvador-orthographic.svg' },
        { name: 'Guatemala',
          flag: 'guatemala-flag.svg',
          emblem: 'guatemala-emblem.svg',
          orthographic: 'guatemala-orthographic.svg' },
        { name: 'Honduras',
          flag: 'honduras-flag.svg',
          emblem: 'honduras-emblem.svg',
          orthographic: 'honduras-orthographic.svg' },
        { name: 'Nicaragua',
          flag: 'nicaragua-flag.svg',
          emblem: 'nicaragua-emblem.svg',
          orthographic: 'nicaragua-orthographic.svg' },
        { name: 'Panama',
          flag: 'panama-flag.svg',
          emblem: 'panama-emblem.svg',
          orthographic: 'panama-orthographic.svg' } ]
    },
    {
      name: 'South America',
      countries: [
        { name: 'Argentina',
          flag: 'argentina-flag.svg',
          emblem: 'argentina-emblem.svg',
          orthographic: 'argentina-orthographic.svg' },
        { name: 'Bolivia',
          flag: 'bolivia-flag.svg',
          emblem: 'bolivia-emblem.gif',
          orthographic: 'bolivia-orthographic.svg' },
        { name: 'Brazil',
          flag: 'brazil-flag.svg',
          emblem: 'brazil-emblem.svg',
          orthographic: 'brazil-orthographic.svg' },
        { name: 'Chile',
          flag: 'chile-flag.svg',
          emblem: 'chile-emblem.svg',
          orthographic: 'chile-orthographic.svg' },
        { name: 'Colombia',
          flag: 'colombia-flag.svg',
          emblem: 'colombia-emblem.svg',
          orthographic: 'colombia-orthographic.svg' },
        { name: 'Ecuador',
          flag: 'ecuador-flag.svg',
          emblem: 'ecuador-emblem.svg',
          orthographic: 'ecuador-orthographic.svg' },
        { name: 'the Falkland Islands (Malvinas)',
          flag: 'falkland-islands-flag.svg',
          emblem: 'falkland-islands-emblem.svg',
          orthographic: 'falkland-islands-orthographic.svg' },
        { name: 'French Guiana',
          flag: 'french-guiana-flag.svg',
          emblem: 'french-guiana-emblem.svg',
          orthographic: 'french-guiana-orthographic.svg' },
        { name: 'Guyana',
          flag: 'guyana-flag.svg',
          emblem: 'guyana-emblem.svg',
          orthographic: 'guyana-orthographic.svg' },
        { name: 'Paraguay',
          flag: 'paraguay-flag.svg',
          emblem: 'paraguay-emblem.svg',
          orthographic: 'paraguay-orthographic.svg' },
        { name: 'Peru',
          flag: 'peru-flag.svg',
          emblem: 'peru-emblem.svg',
          orthographic: 'peru-orthographic.svg' },
        { name: 'Suriname',
          flag: 'suriname-flag.svg',
          emblem: 'suriname-emblem.svg',
          orthographic: 'suriname-orthographic.svg' },
        { name: 'Uruguay',
          flag: 'uruguay-flag.svg',
          emblem: 'uruguay-emblem.svg',
          orthographic: 'uruguay-orthographic.svg' },
        { name: 'Venezuela',
          flag: 'venezuela-flag.svg',
          emblem: 'venezuela-emblem.png',
          orthographic: 'venezuela-orthographic.svg' } ]
    },
    {
      name: 'Northern America',
      countries: [
        { name: 'Bermuda',
          flag: 'bermuda-flag.svg',
          emblem: 'bermuda-emblem.svg',
          orthographic: 'bermuda-orthographic.svg' },
        { name: 'Mexico',
          flag: 'mexico-flag.svg',
          emblem: 'mexico-emblem.svg',
          orthographic: 'mexico-orthographic.svg' },
        { name: 'Canada',
          flag: 'canada-flag.svg',
          emblem: null,
          orthographic: 'canada-orthographic.svg' },
        { name: 'Greenland',
          flag: 'greenland-flag.svg',
          emblem: 'greenland-emblem.svg',
          orthographic: 'greenland-orthographic.svg' },
        { name: 'Saint Pierre and Miquelon',
          flag: 'saint-pierre-and-miquelon-flag.svg',
          emblem: 'saint-pierre-and-miquelon-emblem.svg',
          orthographic: 'saint-pierre-and-miquelon-orthographic.svg' },
        { name: 'United States',
          flag: 'united-states-flag.svg',
          emblem: 'united-states-emblem.svg',
          orthographic: 'united-states-orthographic.svg' }
      ]
    }
  ]};

  var asia = {
    name: 'Asia',
    subRegions: [
    {
      name: 'Central Asia',
      countries: [
        { name: 'Kazakhstan',
          flag: 'kazakhstan-flag.svg',
          emblem: 'kazakhstan-emblem.svg',
          orthographic: 'kazakhstan-orthographic.svg' },
        { name: 'Kyrgyzstan',
          flag: 'kyrgyzstan-flag.svg',
          emblem: 'kyrgyzstan-emblem.svg',
          orthographic: 'kyrgyzstan-orthographic.svg' },
        { name: 'Tajikistan',
          flag: 'tajikistan-flag.svg',
          emblem: 'tajikistan-emblem.svg',
          orthographic: 'tajikistan-orthographic.svg' },
        { name: 'Turkmenistan',
          flag: 'turkmenistan-flag.svg',
          emblem: 'turkmenistan-emblem.svg',
          orthographic: 'turkmenistan-orthographic.svg' },
        { name: 'Uzbekistan',
          flag: 'uzbekistan-flag.svg',
          emblem: 'uzbekistan-emblem.svg',
          orthographic: 'uzbekistan-orthographic.svg' }
      ]
    },
    {
      name: 'Eastern Asia',
      countries: [
        { name: 'China',
          flag: 'china-flag.svg',
          emblem: 'china-emblem.svg',
          orthographic: 'china-orthographic.svg' },
        { name: 'Hong Kong',
          flag: 'hong-kong-flag.svg',
          emblem: 'hong-kong-emblem.svg',
          orthographic: 'hong-kong-orthographic.svg' },
        { name: 'Macau',
          flag: 'macau-flag.svg',
          emblem: 'macau-emblem.svg',
          orthographic: 'macau-orthographic.svg' },
        { name: 'Japan',
          flag: 'japan-flag.svg',
          emblem: 'japan-emblem.svg',
          orthographic: 'japan-orthographic.svg' },
        { name: 'Mongolia',
          flag: 'mongolia-flag.svg',
          emblem: 'mongolia-emblem.svg',
          orthographic: 'mongolia-orthographic.svg' },
        { name: 'North Korea',
          flag: 'north-korea-flag.svg',
          emblem: 'north-korea-emblem.svg',
          orthographic: 'north-korea-orthographic.svg' },
        { name: 'South Korea',
          flag: 'south-korea-flag.svg',
          emblem: 'south-korea-emblem.svg',
          orthographic: 'south-korea-orthographic.svg' },
        { name: 'Taiwan',
          flag: 'taiwan-flag.svg',
          emblem: 'taiwan-emblem.svg',
          orthographic: 'taiwan-orthographic.svg' } ]
    },
    {
      name: 'Southeastern Asia',
      countries: [
        { name: 'Brunei Darussalam',
          flag: 'brunei-flag.svg',
          emblem: 'brunei-emblem.svg',
          orthographic: 'brunei-orthographic.svg' },
        { name: 'Cambodia',
          flag: 'cambodia-flag.svg',
          emblem: 'cambodia-emblem.svg',
          orthographic: 'cambodia-orthographic.svg' },
        { name: 'Indonesia',
          flag: 'indonesia-flag.svg',
          emblem: 'indonesia-emblem.svg',
          orthographic: 'indonesia-orthographic.svg' },
        { name: 'Laos',
          flag: 'laos-flag.svg',
          emblem: 'laos-emblem.svg',
          orthographic: 'laos-orthographic.svg' },
        { name: 'Malaysia',
          flag: 'malaysia-flag.svg',
          emblem: 'malaysia-emblem.svg',
          orthographic: 'malaysia-orthographic.svg' },
        { name: 'Myanmar',
          flag: 'myanmar-flag.svg',
          emblem: 'myanmar-emblem.svg',
          orthographic: 'myanmar-orthographic.svg' },
        { name: 'the Philippines',
          flag: 'philippines-flag.svg',
          emblem: 'philippines-emblem.svg',
          orthographic: 'philippines-orthographic.svg' },
        { name: 'Singapore',
          flag: 'singapore-flag.svg',
          emblem: 'singapore-emblem.svg',
          orthographic: 'singapore-orthographic.svg' },
        { name: 'Thailand',
          flag: 'thailand-flag.svg',
          emblem: 'thailand-emblem.svg',
          orthographic: 'thailand-orthographic.svg' },
        { name: 'Timor-Leste',
          flag: 'timor-leste-flag.svg',
          emblem: 'timor-leste-emblem.svg',
          orthographic: 'timor-leste-orthographic.svg' },
        { name: 'Viet Nam',
          flag: 'vietnam-flag.svg',
          emblem: 'vietnam-emblem.svg',
          orthographic: 'vietnam-orthographic.svg' } ]
    },
    {
      name: 'Southern Asia',
      countries: [
      { name: 'Afghanistan',
        flag: 'afghanistan-flag.svg',
        emblem: 'afghanistan-emblem.svg',
        orthographic: 'afghanistan-orthographic.svg' },
      { name: 'Bangladesh',
        flag: 'bangladesh-flag.svg',
        emblem: 'bangladesh-emblem.svg',
        orthographic: 'bangladesh-orthographic.svg' },
      { name: 'Bhutan',
        flag: 'bhutan-flag.svg',
        emblem: 'bhutan-emblem.svg',
        orthographic: 'bhutan-orthographic.svg' },
      { name: 'India',
        flag: 'india-flag.svg',
        emblem: 'india-emblem.svg',
        orthographic: 'india-orthographic.svg' },
      { name: 'Iran',
        flag: 'iran-flag.svg',
        emblem: 'iran-emblem.svg',
        orthographic: 'iran-orthographic.svg' },
      { name: 'the Maldives',
        flag: 'maldives-flag.svg',
        emblem: 'maldives-emblem.svg',
        orthographic: 'maldives-orthographic.svg' },
      { name: 'Nepal',
        flag: 'nepal-flag.svg',
        emblem: 'nepal-emblem.svg',
        orthographic: 'nepal-orthographic.svg' },
      { name: 'Pakistan',
        flag: 'pakistan-flag.svg',
        emblem: 'pakistan-emblem.svg',
        orthographic: 'pakistan-orthographic.svg' },
      { name: 'Sri Lanka',
        flag: 'sri-lanka-flag.svg',
        emblem: 'sri-lanka-emblem.svg',
        orthographic: 'sri-lanka-orthographic.svg' }
  ]},
    {
      name: 'Western Asia',
      countries: [
      { name: 'Armenia',
        flag: 'armenia-flag.svg',
        emblem: 'armenia-emblem.svg',
        orthographic: 'armenia-orthographic.svg' },
      { name: 'Azerbaijan',
        flag: 'azerbaijan-flag.svg',
        emblem: 'azerbaijan-emblem.svg',
        orthographic: 'azerbaijan-orthographic.svg' },
      { name: 'Bahrain',
        flag: 'bahrain-flag.svg',
        emblem: 'bahrain-emblem.svg',
        orthographic: 'bahrain-orthographic.svg' },
      { name: 'Cyprus',
        flag: 'cyprus-flag.svg',
        emblem: 'cyprus-emblem.svg',
        orthographic: 'cyprus-orthographic.svg' },
      { name: 'Georgia',
        flag: 'georgia-flag.svg',
        emblem: 'georgia-emblem.svg',
        orthographic: 'georgia-orthographic.svg' },
      { name: 'Iraq',
        flag: 'iraq-flag.svg',
        emblem: 'iraq-emblem.svg',
        orthographic: 'iraq-orthographic.svg' },
      { name: 'Israel',
        flag: 'israel-flag.svg',
        emblem: 'israel-emblem.svg',
        orthographic: 'israel-orthographic.svg' },
      { name: 'Jordan',
        flag: 'jordan-flag.svg',
        emblem: 'jordan-emblem.svg',
        orthographic: 'jordan-orthographic.svg' },
      { name: 'Kuwait',
        flag: 'kuwait-flag.svg',
        emblem: 'kuwait-emblem.svg',
        orthographic: 'kuwait-orthographic.svg' },
      { name: 'Lebanon',
        flag: 'lebanon-flag.svg',
        emblem: 'lebanon-emblem.svg',
        orthographic: 'lebanon-orthographic.svg' },
      { name: 'Oman',
        flag: 'oman-flag.svg',
        emblem: 'oman-emblem.svg',
        orthographic: 'oman-orthographic.svg' },
      { name: 'Qatar',
        flag: 'qatar-flag.svg',
        emblem: 'qatar-emblem.svg',
        orthographic: 'qatar-orthographic.svg' },
      { name: 'Saudi Arabia',
        flag: 'saudi-arabia-flag.svg',
        emblem: 'saudi-arabia-emblem.svg',
        orthographic: 'saudi-arabia-orthographic.svg' },
      { name: 'the State of Palestine',
        flag: 'palestine-flag.svg',
        emblem: 'palestine-emblem.svg',
        orthographic: 'palestine-orthographic.svg' },
      { name: 'Syria',
        flag: 'syria-flag.svg',
        emblem: 'syria-emblem.svg',
        orthographic: 'syria-orthographic.svg' },
      { name: 'Turkey',
        flag: 'turkey-flag.svg',
        emblem: null,
        orthographic: 'turkey-orthographic.svg' },
      { name: 'the United Arab Emirates',
        flag: 'united-arab-emirates-flag.svg',
        emblem: 'united-arab-emirates-emblem.svg',
        orthographic: 'united-arab-emirates-orthographic.svg' },
      { name: 'Yemen',
        flag: 'yemen-flag.svg',
        emblem: 'yemen-emblem.svg',
        orthographic: 'yemen-orthographic.svg' }
   ]}
  ]};

  var europe = {
    name: 'Europe',
    subRegions: [{
      name: 'Eastern Europe',
      countries: [
        { name: 'Belarus',
          flag: 'belarus-flag.svg',
          emblem: 'belarus-emblem.svg',
          orthographic: 'belarus-orthographic.svg' },
        { name: 'Bulgaria',
          flag: 'bulgaria-flag.svg',
          emblem: 'bulgaria-emblem.svg',
          orthographic: 'bulgaria-orthographic.svg' },
        { name: 'the Czech Republic',
          flag: 'czech-republic-flag.svg',
          emblem: 'czech-republic-emblem.svg',
          orthographic: 'czech-republic-orthographic.svg' },
        { name: 'Hungary',
          flag: 'hungary-flag.svg',
          emblem: 'hungary-emblem.svg',
          orthographic: 'hungary-orthographic.svg' },
        { name: 'Poland',
          flag: 'poland-flag.svg',
          emblem: 'poland-emblem.svg',
          orthographic: 'poland-orthographic.svg' },
        { name: 'the Republic of Moldova',
          flag: 'moldova-flag.svg',
          emblem: 'moldova-emblem.svg',
          orthographic: 'moldova-orthographic.png' },
        { name: 'Romania',
          flag: 'romania-flag.svg',
          emblem: 'romania-emblem.svg',
          orthographic: 'romania-orthographic.svg' },
        { name: 'the Russian Federation',
          flag: 'russia-flag.svg',
          emblem: 'russia-emblem.svg',
          orthographic: 'russia-orthographic.svg' },
        { name: 'Slovakia',
          flag: 'slovakia-flag.svg',
          emblem: 'slovakia-emblem.svg',
          orthographic: 'slovakia-orthographic.svg' },
        { name: 'Ukraine',
          flag: 'ukraine-flag.svg',
          emblem: 'ukraine-emblem.svg',
          orthographic: 'ukraine-orthographic.svg' }
      ]},
    {
      name: 'Northern Europe',
      countries: [
      { name: 'the Aland Islands',
        flag: 'aland-islands-flag.svg',
        emblem: 'aland-islands-emblem.svg',
        orthographic: 'aland-islands-orthographic.png' },
      { name: 'Denmark',
        flag: 'denmark-flag.svg',
        emblem: 'denmark-emblem.svg',
        orthographic: 'denmark-orthographic.svg' },
      { name: 'Estonia',
        flag: 'estonia-flag.svg',
        emblem: 'estonia-emblem.svg',
        orthographic: 'estonia-orthographic.svg' },
      { name: 'the Faroe Islands',
        flag: 'faroe-islands-flag.svg',
        emblem: 'faroe-islands-emblem.svg',
        orthographic: 'faroe-islands-orthographic.svg' },
      { name: 'Finland',
        flag: 'finland-flag.svg',
        emblem: 'finland-emblem.svg',
        orthographic: 'finland-orthographic.svg' },
      { name: 'Iceland',
        flag: 'iceland-flag.svg',
        emblem: 'iceland-emblem.svg',
        orthographic: 'iceland-orthographic.svg' },
      { name: 'the Republic of Ireland',
        flag: 'ireland-flag.svg',
        emblem: 'ireland-emblem.svg',
        orthographic: 'ireland-orthographic.svg' },
      { name: 'the Isle of Man',
        flag: 'isle-of-man-flag.svg',
        emblem: 'isle-of-man-emblem.svg',
        orthographic: 'isle-of-man-orthographic.svg' },
      { name: 'Jersey',
        flag: 'jersey-flag.svg',
        emblem: 'jersey-emblem.svg',
        orthographic: 'jersey-orthographic.svg' },
      { name: 'Latvia',
        flag: 'latvia-flag.svg',
        emblem: 'latvia-emblem.svg',
        orthographic: 'latvia-orthographic.svg' },
      { name: 'Lithuania',
        flag: 'lithuania-flag.svg',
        emblem: 'lithuania-emblem.svg',
        orthographic: 'lithuania-orthographic.svg' },
      { name: 'Norway',
        flag: 'norway-flag.svg',
        emblem: 'norway-emblem.svg',
        orthographic: 'norway-orthographic.svg' },
      { name: 'Sweden',
        flag: 'sweden-flag.svg',
        emblem: 'sweden-emblem.svg',
        orthographic: 'sweden-orthographic.svg' },
      { name: 'the United Kingdom',
        flag: 'united-kingdom-flag.svg',
        emblem: 'united-kingdom-emblem.svg',
        orthographic: 'united-kingdom-orthographic.svg' } ]
    },
    {
      name: 'Southern Europe',
      countries: [
        { name: 'Albania',
          flag: 'albania-flag.svg',
          emblem: 'albania-emblem.svg',
          orthographic: 'albania-orthographic.svg' },
        { name: 'Andorra',
          flag: 'andorra-flag.svg',
          emblem: 'andorra-emblem.svg',
          orthographic: 'andorra-orthographic.png' },
        { name: 'Bosnia and Herzegovina',
          flag: 'bosnia-and-herzegovina-flag.svg',
          emblem: 'bosnia-and-herzegovina-emblem.svg',
          orthographic: 'bosnia-and-herzegovina-orthographic.svg' },
        { name: 'Croatia',
          flag: 'croatia-flag.svg',
          emblem: 'croatia-emblem.svg',
          orthographic: 'croatia-orthographic.svg' },
        { name: 'Gibraltar',
          flag: 'gibraltar-flag.svg',
          emblem: 'gibraltar-emblem.svg',
          orthographic: 'gibraltar-orthographic.svg' },
        { name: 'Greece',
          flag: 'greece-flag.svg',
          emblem: 'greece-emblem.svg',
          orthographic: 'greece-orthographic.svg' },
        { name: 'Italy',
          flag: 'italy-flag.svg',
          emblem: 'italy-emblem.svg',
          orthographic: 'italy-orthographic.svg' },
        { name: 'the Republic of Macedonia',
          flag: 'macedonia-flag.svg',
          emblem: 'macedonia-emblem.svg',
          orthographic: 'macedonia-orthographic.svg' },
        { name: 'Malta',
          flag: 'malta-flag.svg',
          emblem: 'malta-emblem.svg',
          orthographic: 'malta-orthographic.svg' },
        { name: 'Montenegro',
          flag: 'montenegro-flag.svg',
          emblem: 'montenegro-emblem.svg',
          orthographic: 'montenegro-orthographic.svg' },
        { name: 'Portugal',
          flag: 'portugal-flag.svg',
          emblem: 'portugal-emblem.svg',
          orthographic: 'portugal-orthographic.svg' },
        { name: 'San Marino',
          flag: 'san-marino-flag.svg',
          emblem: 'san-marino-emblem.svg',
          orthographic: 'san-marino-orthographic.png' },
        { name: 'Serbia',
          flag: 'serbia-flag.svg',
          emblem: 'serbia-emblem.svg',
          orthographic: 'serbia-orthographic.png' },
        { name: 'Slovenia',
          flag: 'slovenia-flag.svg',
          emblem: 'slovenia-emblem.svg',
          orthographic: 'slovenia-orthographic.svg' },
        { name: 'Spain',
          flag: 'spain-flag.svg',
          emblem: 'spain-emblem.svg',
          orthographic: 'spain-orthographic.svg' },
        { name: 'Vatican City',
          flag: 'vatican-city-flag.svg',
          emblem: 'vatican-city-emblem.svg',
          orthographic: 'vatican-city-orthographic.svg' } ]
    },
    {
      name: 'Western Europe',
      countries: [
        { name: 'Austria',
          flag: 'austria-flag.svg',
          emblem: 'austria-emblem.svg',
          orthographic: 'austria-orthographic.svg' },
        { name: 'Belgium',
          flag: 'belgium-flag.svg',
          emblem: 'belgium-emblem.svg',
          orthographic: 'belgium-orthographic.svg' },
        { name: 'France',
          flag: 'france-flag.svg',
          emblem: 'france-emblem.svg',
          orthographic: 'france-orthographic.svg' },
        { name: 'Germany',
          flag: 'germany-flag.svg',
          emblem: 'germany-emblem.svg',
          orthographic: 'germany-orthographic.svg' },
        { name: 'Liechtenstein',
          flag: 'liechtenstein-flag.svg',
          emblem: 'liechtenstein-emblem.svg',
          orthographic: 'liechtenstein-orthographic.svg' },
        { name: 'Luxembourg',
          flag: 'luxembourg-flag.svg',
          emblem: 'luxembourg-emblem.svg',
          orthographic: 'luxembourg-orthographic.svg' },
        { name: 'Monaco',
          flag: 'monaco-flag.svg',
          emblem: 'monaco-emblem.svg',
          orthographic: 'monaco-orthographic.png' },
        { name: 'the Netherlands',
          flag: 'netherlands-flag.svg',
          emblem: 'netherlands-emblem.svg',
          orthographic: 'netherlands-orthographic.svg' },
        { name: 'Switzerland',
          flag: 'switzerland-flag.svg',
          emblem: 'switzerland-emblem.svg',
          orthographic: 'switzerland-orthographic.svg' }
        ]
    }
  ]};

  var oceania = {
    name: 'Oceania',
    subRegions: [
    {
      name: 'Australia, New Zealand, and Melanesia',
      countries: [
      { name: 'Australia',
        flag: 'australia-flag.svg',
        emblem: 'australia-emblem.svg',
        orthographic: 'australia-orthographic.svg' },
      { name: 'New Zealand',
        flag: 'new-zealand-flag.svg',
        emblem: 'new-zealand-emblem.svg',
        orthographic: 'new-zealand-orthographic.svg' },
      { name: 'Fiji',
        flag: 'fiji-flag.svg',
        emblem: 'fiji-emblem.svg',
        orthographic: 'fiji-orthographic.svg' },
      { name: 'New Caledonia (France)',
        flag: 'new-caledonia-flag.svg',
        emblem: 'new-caledonia-emblem.svg',
        orthographic: 'new-caledonia-orthographic.svg' },
      { name: 'Papua New Guinea',
        flag: 'papua-new-guinea-flag.svg',
        emblem: 'papua-new-guinea-emblem.svg',
        orthographic: 'papua-new-guinea-orthographic.svg' },
      { name: 'the Solomon Islands',
        flag: 'solomon-islands-flag.svg',
        emblem: 'solomon-islands-emblem.svg',
        orthographic: 'solomon-islands-orthographic.svg' },
      { name: 'Vanuatu',
        flag: 'vanuatu-flag.svg',
        emblem: 'vanuatu-emblem.svg',
        orthographic: 'vanuatu-orthographic.svg' }
      ]},
    {
      name: 'Micronesia',
      countries: [
        { name: 'Guam (USA)',
          flag: 'guam-flag.svg',
          emblem: 'guam-emblem.svg',
          orthographic: 'guam-orthographic.svg' },
        { name: 'Kiribati',
          flag: 'kiribati-flag.svg',
          emblem: 'kiribati-emblem.svg',
          orthographic: 'kiribati-orthographic.svg' },
        { name: 'the Marshall Islands',
          flag: 'marshall-islands-flag.svg',
          emblem: 'marshall-islands-emblem.svg',
          orthographic: 'marshall-islands-orthographic.svg' },
        { name: 'the Federated States of Micronesia',
          flag: 'federated-states-of-micronesia-flag.svg',
          emblem: 'federated-states-of-micronesia-emblem.svg',
          orthographic: 'federated-states-of-micronesia-orthographic.svg' },
        { name: 'Nauru',
          flag: 'nauru-flag.svg',
          emblem: 'nauru-emblem.svg',
          orthographic: 'nauru-orthographic.svg' },
        { name: 'the Northern Mariana Islands (USA)',
          flag: 'northern-mariana-islands-flag.svg',
          emblem: 'northern-mariana-islands-emblem.png',
          orthographic: 'northern-mariana-islands-orthographic.svg' },
        { name: 'Palau',
          flag: 'palau-flag.svg',
          emblem: 'palau-emblem.svg',
          orthographic: 'palau-orthographic.png' }
        ]},
    {
      name: 'Polynesia',
      countries: [
        { name: 'American Samoa (USA)',
          flag: 'american-samoa-flag.svg',
          emblem: 'american-samoa-emblem.svg',
          orthographic: 'american-samoa-orthographic.svg' },
        { name: 'the Cook Islands (New Zealand)',
          flag: 'cook-islands-flag.svg',
          emblem: 'cook-islands-emblem.svg',
          orthographic: 'cook-islands-orthographic.svg' },
        { name: 'French Polynesia (France)',
          flag: 'french-polynesia-flag.svg',
          emblem: 'french-polynesia-emblem.svg',
          orthographic: 'french-polynesia-orthographic.svg' },
        { name: 'Niue (New Zealand)',
          flag: 'niue-flag.svg',
          emblem: 'niue-emblem.svg',
          orthographic: 'niue-orthographic.svg' },
        { name: 'Samoa',
          flag: 'samoa-flag.svg',
          emblem: 'samoa-emblem.svg',
          orthographic: 'samoa-orthographic.svg' },
        { name: 'Tokelau (New Zealand)',
          flag: 'tokelau-flag.svg',
          emblem: 'tokelau-emblem.svg',
          orthographic: 'tokelau-orthographic.svg' },
        { name: 'Tonga',
          flag: 'tonga-flag.svg',
          emblem: 'tonga-emblem.svg',
          orthographic: 'tonga-orthographic.svg' },
        { name: 'Tuvalu',
          flag: 'tuvalu-flag.svg',
          emblem: 'tuvalu-emblem.svg',
          orthographic: 'tuvalu-orthographic.svg' },
        { name: 'Wallis and Futuna',
          flag: 'wallis-and-futuna-flag.svg',
          emblem: 'wallis-and-futuna-emblem.svg',
          orthographic: 'wallis-and-futuna-orthographic.svg' }
        ]}
  ]};

  return [americas, africa, asia, europe, oceania];
}
